# Generated by Django 5.2.8 on 2025-12-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(help_text='Nombre de quien reporta', max_length=100)),
                ('area', models.CharField(blank=True, help_text='Área o Departamento (Opcional)', max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('FALLA_EQUIPO', 'Falla de Equipo'), ('RED', 'Falla de Red/Internet'), ('SOFTWARE', 'Software / Programas'), ('IMPRESORA', 'Impresora / Escáner'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField(help_text='Detalle del problema')),
                ('evidencia', models.ImageField(blank=True, help_text='Captura de pantalla o foto (Opcional)', null=True, upload_to='evidencias/')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Revisión'), ('RESUELTO', 'Resuelto'), ('DESCARTADO', 'Descartado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('solucion_tecnica', models.TextField(blank=True, help_text='Descripción de lo realizado para solucionar (Llenado por Admin)', null=True)),
            ],
            options={
                'verbose_name': 'Reporte de Incidencia',
                'verbose_name_plural': 'Reportes de Incidencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
