# Generated by Django 5.2.8 on 2025-12-16 00:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(help_text='Código interno de inventario (Etiqueta)', max_length=50, unique=True)),
                ('serial', models.CharField(blank=True, help_text='Serial del fabricante', max_length=100, null=True, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(help_text='Ubicación actual (ej: Oficina Gerencia)', max_length=150)),
                ('responsable', models.CharField(blank=True, help_text='Nombre de la persona responsable actual', max_length=150, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DISPONIBLE', 'Disponible'), ('EN_REPARACION', 'En Reparación'), ('DAÑADO', 'Dañado'), ('BAJA', 'De Baja')], default='DISPONIBLE', max_length=20)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('garantia_hasta', models.DateField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True, help_text='ram: 8gb, disco: ssd 256gb, etc.', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='inventario.categoria')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ASIGNACION', 'Asignación'), ('TRASLADO', 'Traslado'), ('DEVOLUCION', 'Devolución'), ('REPARACION', 'Envío a Reparación'), ('BAJA', 'Dar de Baja')], max_length=20)),
                ('origen', models.CharField(help_text='Ubicación anterior', max_length=150)),
                ('destino', models.CharField(help_text='Nueva ubicación', max_length=150)),
                ('responsable', models.CharField(blank=True, help_text='Persona que recibe el equipo', max_length=150, null=True)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.dispositivo')),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
