# Generated by Django 5.2.8 on 2025-12-16 01:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], default='PREVENTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('fecha_programada', models.DateField(default=django.utils.timezone.now, help_text='Fecha planeada para el mantenimiento')),
                ('fecha_realizacion', models.DateTimeField(blank=True, help_text='Fecha real de ejecución', null=True)),
                ('descripcion_falla', models.TextField(blank=True, help_text='Descripción del problema (Correctivo) o tareas a realizar (Preventivo)', null=True)),
                ('acciones_realizadas', models.TextField(blank=True, help_text='Reporte técnico de lo realizado', null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo total del servicio/repuestos', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.dispositivo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
