# Generated by Django 5.2.8 on 2025-11-16 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre o identificador único para el disco (ej: 'Backup 2023').", max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('HDD', 'Disco Duro (HDD)'), ('SSD', 'Unidad de Estado Sólido (SSD)'), ('CD/DVD', 'CD / DVD'), ('OTRO', 'Otro')], default='HDD', help_text='Tipo de disco.', max_length=10)),
                ('tamanio_gb', models.DecimalField(decimal_places=2, help_text='Tamaño total del disco en Gigabytes (GB).', max_digits=7)),
                ('descripcion', models.TextField(blank=True, help_text='Notas adicionales o descripción del contenido general del disco.')),
            ],
            options={
                'verbose_name': 'Disco',
                'verbose_name_plural': 'Discos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del archivo o carpeta.', max_length=255)),
                ('fecha_modificacion', models.DateField(help_text='Fecha de última modificación del contenido.')),
                ('peso_gb', models.DecimalField(decimal_places=2, help_text='Peso del contenido en Gigabytes (GB).', max_digits=7)),
                ('disco', models.ForeignKey(help_text='El disco al que pertenece este contenido.', on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='discos.disco')),
            ],
            options={
                'verbose_name': 'Contenido de Disco',
                'verbose_name_plural': 'Contenidos de Discos',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
