# Generated by Django 5.2.8 on 2025-12-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('EN_RIESGO', 'En Riesgo'), ('DANADO', 'Dañado')], default='BUENO', help_text='Estado físico/operativo del disco.', max_length=10),
        ),
    ]
